appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZInhceh7OgPvmkatbJqg2dOzsw5jEjcUnGTev43wtbX+j4tenXi1GGEb/JNgfUpHVknmTCg8h8uI/h5Jsg4cldvQWFeAPRlVb5y0II/QTpibcEBcQEBs1+DqWgsbaZvjyppAqk/MFKotjO3H5gaw6vXQn+UfQgiD0tWYZeSa3VPppfGNC+d+6MFVes84IBihA+t5nKhZeHRIKRLqfs1UVIP6wvaUtUdpPz2/ygGaTM4G+HcrFWhnWmtN4gtQS1TkNF956VbCxWu004UaGa0y0zh7HMXU5jzLi+EsKJBScwahwgwxse364o7c/0KU8d66a3rRrbX4vFXBtsijBzScebbApG5Y6OOXNygqWN826pB1rDxlx9gMYNegdL/1IlLsNRCteNvDMwvMVMnvZTqUxe8WPj3U2edkqGLwDpQm9OquCfMkCEMkL6MWMOFZsYX70slqad128RS0wHYy6bQJ8FDMQs9MzLBDRI4T8o3YrgCCB6ACo7699h5KjKk6RF4SOfK6a4IviRXHHpk2KMixXPHgTaBIrEdZBWTkcOzp/vqn+EuFcVu8upa5/GZ95wZHghrwjY85AEvHyNtYhQgb9CMIUyzoMevAsFN8/0c3Hy7g815BAhd9E2mNTrNrtIcwYHKVJwI97Gos7aJaHUcOf1FqwxqPGb/+A6O8+IfU8QA=}
